require("plugins")
require("config")
require("key_bindings")
require("plugins_config.nvim_tree_conf")
require("plugins_config.lsp_conf")
require("plugins_config.telescope_conf")
require("plugins_config.neomake_conf")
